#+SETUPFILE: ../setup.org
#+TITLE: Orders of existence
#+DATE: 2021-05-26
#+FILETAGS: :mathematics:philosophy:

What does naming big numbers have to do with the technological sophistication of a society?

There is a famous [[https://www.scottaaronson.com/writings/bignumbers.html][blog post]] by Scott Aaronson in which he posits that we can use our ability to describe bigger and bigger finite numbers[fn:1] as a marker of our society's advancement in the theoretico-quantitative pursuits, and in the empirical and deductive fields more generally. It goes like this: ask a room of children[fn:2] to write down the biggest number they can on an index card; the winner is the one who can name the biggest number. One child might write "1" followed by as many zeros as they can fit within the index card; another child might be a tad more clever and fill it with nines. Asking older and wiser students to play the game now, a clever secondary student might use $$\exp(999\ldots 9)$$, while a smarter classmate might know that `^` is notation for exponentiation, and fill the card with `9^9^...^9`. A university student concentrating in mathematics might be familiar with [[https://en.wikipedia.org/wiki/Tetration][tetration]], [[https://en.wikipedia.org/wiki/Pentation][pentation]], and the other hyperexponentiation functions, while a computer science concentrator might invoke the [[https://en.wikipedia.org/wiki/Ackermann_function][Ackermann function]]. And so on. Note how each guess gets progressively more advanced, and the intellectual building blocks needed to generate and understand each proposal require progressively more mathematical and logical theory.

If Aaronson's numbers game is one metric for viewing the progress of broader society's cognitive frontier, I would like to propose another gamified metric, this time straddling the edge between the natural, the social, and the metaphysical. The game is this: the first player, the /proposer/, must provide the most general criterion for existence; the second player, an /adversary/, must name a specific concept that does not meet that criterion. All of the tools of science, logic, mathematics, and the social sciences, and any field more broadly are available to either player. The rules are kept intentionally vague to stir debate.

One might imagine, for instance, that it suffices for the proposer to claim that something exists if it is composed of atoms. /But what about neutrinos and quarks?/, the adversary replies.

/Very well/, the proposer reacts; /how about anything composed of subatomic particles/[fn:3]? Adversary: /Your approach fails to account for the Ship of Theseus[fn:4] problem. By your account, since humans may replace all of their cells within a lifetime, a single human would not even exist!/

You might be able to imagine how it proceeds from here: the first player constructs a criterion that allows for locality of space and time as a criterion. Eventually, the second player will think of things ephemeral: the economy; the internet; aesthetics; mathematics itself. As retorts, the proposer includes the class of all concepts possessing an attached field of human academic study or a related profession; all concepts that are quantitatively measured in some aspect; all concepts ever dreamt of by at least one human being; and so on.

Finally, after several rounds, the first player might take the bold step of defining a criterion thusly: enumerate all possible formal languages --- countable as they are --- and say that a concept /exists/ if there exists at least one well-formed formula that describes it within at least one language, adjoining the class of all natural language nouns as primitives in some suitable (model-based) sense. This criterion would include everything governed by the [[https://en.wikipedia.org/wiki/Wightman_axioms][Wightman axioms]] (and any correct or incorrect physical theory, at that), all potential correct and incorrect formal models of the economy, all precise descriptions of aesthetics, and so on. But does this "enumeration over languages" approach open up the possibility of a [[https://en.wikipedia.org/wiki/Halting_problem][diagonalization-style argument]] that the adversary can use to construct a formal object outside of this criterion?

Food for thought, dear reader; the next move is yours. Can you think of a more general criterion for existence? How would you construct a concept that cannot be formed from at least one formula in at least one descriptive language?


[fn:1] Arguably, we can extend the game to bigger and bigger /infinite/ numbers as well; mathematical set theory is full of differently-sized infinities, such as the cardinality of the natural numbers ($\aleph_0$), the cardinality of the real numbers ($$\aleph_1 > aleph_0$$), and so on.

[fn:2] ...Or adults! Or better yet, a room of combinatorialists!

[fn:3] ...Or strings, presuming some variant of string theory is valid.

[fn:4] The [[https://en.wikipedia.org/wiki/Ship_of_Theseus][Ship of Theseus]] paradox asks: if a given ship has its components replaced gradually over time, component-by-component, is it still the same ship?
